packages:
  - 'apps/*'
  - 'packages/*'
  - 'qa/playwright'

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - '@scarf/scarf'
  - bcrypt
  - prisma
  - sharp
  - unrs-resolver
