"use client";

import { AdminLayout } from "./AdminLayout";
import { 
  FileText, 
  Download, 
  Search, 
  Filter, 
  Calendar, 
  Clock, 
  ChevronRight, 
  BarChart3, 
  Users, 
  TrendingUp,
  AlertCircle,
  Play,
  FileCheck,
  ShieldCheck,
  Package
} from "lucide-react";

const ReportCard = ({ type, id, title, desc, icon: Icon, color }: any) => (
  <div className="bg-white p-6 rounded-2xl border border-slate-200 shadow-sm hover:shadow-md transition-all group">
    <div className="flex justify-between items-start mb-4">
      <div className={`p-2 rounded-lg text-[10px] font-bold uppercase tracking-widest ${color}`}>
        {type}
      </div>
      <span className="text-[10px] text-slate-400 font-bold">{id}</span>
    </div>
    <h4 className="text-lg font-bold text-slate-900 group-hover:text-blue-600 transition-colors mb-2">{title}</h4>
    <p className="text-xs text-slate-500 leading-relaxed mb-6 h-12 overflow-hidden">{desc}</p>
    
    <button className="w-full flex items-center justify-center gap-2 py-2.5 bg-slate-50 hover:bg-blue-600 hover:text-white text-blue-600 rounded-xl text-xs font-bold transition-all">
      <Play className="w-3 h-3" /> Run Export
    </button>
  </div>
);

export default function Reports() {
  return (
    <AdminLayout activeTab="reports" title="Reports Catalog">
      <div className="mb-8">
        <p className="text-sm text-slate-500">Generate, view, and export standard system reports for compliance and auditing.</p>
      </div>

      {/* Permissions Banner */}
      <div className="bg-blue-50 border border-blue-100 rounded-2xl p-4 mb-8 flex items-start gap-4">
        <div className="p-2 bg-blue-100 rounded-lg">
          <ShieldCheck className="w-5 h-5 text-blue-600" />
        </div>
        <div>
          <h4 className="text-sm font-bold text-blue-900">Export Permissions Validated</h4>
          <p className="text-xs text-blue-700 mt-1 leading-relaxed">
            You have active roles granting <code className="bg-blue-100 px-1 py-0.5 rounded">reports:view</code> and <code className="bg-blue-100 px-1 py-0.5 rounded">reports:export</code> permissions.
          </p>
        </div>
      </div>

      {/* Category Tabs */}
      <div className="flex gap-4 mb-8 border-b border-slate-200 overflow-x-auto no-scrollbar">
        {["All", "Tender", "Vendor", "Financial", "Audit", "Operations"].map((tab) => (
          <button 
            key={tab}
            className={`px-4 pb-4 text-sm font-bold transition-all relative ${
              tab === "All" ? "text-blue-600" : "text-slate-400 hover:text-slate-900"
            }`}
          >
            {tab}
            {tab === "All" && <div className="absolute bottom-0 left-0 w-full h-[3px] bg-blue-600 rounded-t-full"></div>}
          </button>
        ))}
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 mb-12">
        <ReportCard 
          type="Tender" 
          id="RPT-T01" 
          title="Active Tenders Status" 
          desc="Comprehensive overview of all currently active tenders, including stage, current highest bidder, and remaining timeline."
          color="bg-blue-100 text-blue-700"
        />
        <ReportCard 
          type="Vendor" 
          id="RPT-V04" 
          title="Vendor Compliance Matrix" 
          desc="Detailed assessment of vendor document expirations, compliance flags, and pre-qualification status across all registered entities."
          color="bg-blue-100 text-blue-700"
        />
        <ReportCard 
          type="Financial" 
          id="RPT-F02" 
          title="Award Savings Analysis" 
          desc="Comparative analysis of initial budgetary estimates versus final awarded contract values for the current fiscal quarter."
          color="bg-emerald-100 text-emerald-700"
        />
      </div>

      {/* Recent Activity / Exports */}
      <div>
        <h3 className="text-lg font-bold text-slate-900 mb-6">Recent Exports</h3>
        <div className="bg-white rounded-2xl border border-slate-200 shadow-sm overflow-hidden">
          <table className="w-full text-left border-collapse">
            <thead>
              <tr className="bg-slate-50/50 text-[11px] font-bold text-slate-500 uppercase tracking-widest border-b border-slate-100">
                <th className="py-4 px-6 font-bold">Report Name</th>
                <th className="py-4 px-6 font-bold">Format</th>
                <th className="py-4 px-6 font-bold">Generated By</th>
                <th className="py-4 px-6 font-bold">Date / Time</th>
                <th className="py-4 px-6 font-bold text-right">Action</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-50">
              {[
                { name: "Active Tenders Status", format: "XLSX", by: "System Admin", time: "Today, 09:41 AM" },
                { name: "Vendor Compliance Matrix", format: "PDF", by: "J. Doe (Audit)", time: "Yesterday, 14:20 PM" },
              ].map((row, i) => (
                <tr key={i} className="hover:bg-slate-50 transition-colors">
                  <td className="py-4 px-6">
                    <p className="text-sm font-bold text-slate-900">{row.name}</p>
                  </td>
                  <td className="py-4 px-6">
                    <span className="px-2 py-0.5 bg-slate-100 text-slate-600 text-[10px] font-bold rounded">{row.format}</span>
                  </td>
                  <td className="py-4 px-6">
                    <p className="text-sm text-slate-600">{row.by}</p>
                  </td>
                  <td className="py-4 px-6">
                    <p className="text-sm text-slate-500">{row.time}</p>
                  </td>
                  <td className="py-4 px-6 text-right">
                    <button className="text-xs font-bold text-blue-600 hover:underline">Download</button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </AdminLayout>
  );
}
